const set17IconModules = import.meta.glob("../assets/Champions/set17/*.png", {
  eager: true,
  import: "default",
}) as Record<string, any>;

function getSet17Icon(fileName: string) {
  const icon = set17IconModules[`../assets/Champions/set17/${fileName}.png`];

  if (!icon) {
    throw new Error(`Missing Set 17 champion icon: ${fileName}.png`);
  }

  return icon;
}

export const set17ChampionAssets: Record<string, any> = {
  "Aatrox": getSet17Icon("Aatrox"),
  "Akali": getSet17Icon("Akali"),
  "Aurelion Sol": getSet17Icon("AurelionSol"),
  "Aurora": getSet17Icon("Aurora"),
  "Bard": getSet17Icon("Bard"),
  "Bel'Veth": getSet17Icon("Belveth"),
  "Blitzcrank": getSet17Icon("Blitzcrank"),
  "Briar": getSet17Icon("Briar"),
  "Caitlyn": getSet17Icon("Caitlyn"),
  "Cho'Gath": getSet17Icon("Chogath"),
  "Corki": getSet17Icon("Corki"),
  "Diana": getSet17Icon("Diana"),
  "Ezreal": getSet17Icon("Ezreal"),
  "Fiora": getSet17Icon("Fiora"),
  "Fizz": getSet17Icon("Fizz"),
  "Gnar": getSet17Icon("Gnar"),
  "Gragas": getSet17Icon("Gragas"),
  "Graves": getSet17Icon("Graves"),
  "Gwen": getSet17Icon("Gwen"),
  "Illaoi": getSet17Icon("Illaoi"),
  "Jax": getSet17Icon("Jax"),
  "Jhin": getSet17Icon("Jhin"),
  "Jinx": getSet17Icon("Jinx"),
  "Kai'Sa": getSet17Icon("Kaisa"),
  "Karma": getSet17Icon("Karma"),
  "Kindred": getSet17Icon("Kindred"),
  "LeBlanc": getSet17Icon("Leblanc"),
  "Leona": getSet17Icon("Leona"),
  "Lissandra": getSet17Icon("Lissandra"),
  "Lulu": getSet17Icon("Lulu"),
  "Maokai": getSet17Icon("Maokai"),
  "Master Yi": getSet17Icon("MasterYi"),
  "Meepsie": getSet17Icon("IvernMinion"),
  "Milio": getSet17Icon("Milio"),
  "Miss Fortune": getSet17Icon("MissFortune"),
  "Mordekaiser": getSet17Icon("Mordekaiser"),
  "Morgana": getSet17Icon("Morgana"),
  "Nami": getSet17Icon("Nami"),
  "Nasus": getSet17Icon("Nasus"),
  "Nunu & Willump": getSet17Icon("Nunu"),
  "Ornn": getSet17Icon("Ornn"),
  "Pantheon": getSet17Icon("Pantheon"),
  "Poppy": getSet17Icon("Poppy"),
  "Pyke": getSet17Icon("Pyke"),
  "Rammus": getSet17Icon("Rammus"),
  "Rek'Sai": getSet17Icon("RekSai"),
  "Rhaast": getSet17Icon("Rhaast"),
  "Riven": getSet17Icon("Riven"),
  "Samira": getSet17Icon("Samira"),
  "Shen": getSet17Icon("Shen"),
  "Sona": getSet17Icon("Sona"),
  "Tahm Kench": getSet17Icon("TahmKench"),
  "Talon": getSet17Icon("Talon"),
  "Teemo": getSet17Icon("Teemo"),
  "The Mighty Mech": getSet17Icon("Galio"),
  "Twisted Fate": getSet17Icon("TwistedFate"),
  "Urgot": getSet17Icon("Urgot"),
  "Veigar": getSet17Icon("Veigar"),
  "Vex": getSet17Icon("Vex"),
  "Viktor": getSet17Icon("Viktor"),
  "Xayah": getSet17Icon("Xayah"),
  "Zed": getSet17Icon("Zed"),
  "Zoe": getSet17Icon("Zoe"),
};

export const set17ChampionRarity: Record<string, number> = {
  "Aatrox": 1,
  "Akali": 2,
  "Aurelion Sol": 4,
  "Aurora": 3,
  "Bard": 5,
  "Bel'Veth": 2,
  "Blitzcrank": 5,
  "Briar": 1,
  "Caitlyn": 1,
  "Cho'Gath": 1,
  "Corki": 4,
  "Diana": 3,
  "Ezreal": 1,
  "Fiora": 5,
  "Fizz": 3,
  "Gnar": 2,
  "Gragas": 2,
  "Graves": 5,
  "Gwen": 2,
  "Illaoi": 3,
  "Jax": 2,
  "Jhin": 5,
  "Jinx": 2,
  "Kai'Sa": 3,
  "Karma": 4,
  "Kindred": 4,
  "LeBlanc": 4,
  "Leona": 1,
  "Lissandra": 1,
  "Lulu": 3,
  "Maokai": 3,
  "Master Yi": 4,
  "Meepsie": 2,
  "Milio": 2,
  "Miss Fortune": 3,
  "Mordekaiser": 2,
  "Morgana": 5,
  "Nami": 4,
  "Nasus": 1,
  "Nunu & Willump": 4,
  "Ornn": 3,
  "Pantheon": 2,
  "Poppy": 1,
  "Pyke": 2,
  "Rammus": 4,
  "Rek'Sai": 1,
  "Rhaast": 3,
  "Riven": 4,
  "Samira": 3,
  "Shen": 5,
  "Sona": 5,
  "Tahm Kench": 4,
  "Talon": 1,
  "Teemo": 1,
  "The Mighty Mech": 4,
  "Twisted Fate": 1,
  "Urgot": 3,
  "Veigar": 1,
  "Vex": 5,
  "Viktor": 3,
  "Xayah": 4,
  "Zed": 5,
  "Zoe": 2,
};

export function isSet17Champion(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(set17ChampionAssets, name);
}

