export const set17ItemAssets: Record<string, string> = {
  'Protector\'s Vow': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_frozenheart.tft_set13.png',
  'Spirit Visage': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_spiritvisagerr.tft_tft14_5.png',
  'Crownguard': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_crownguard.tft_set13.png',
  'Steadfast Heart': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_nightharvester.tft_set13.png',
  'Bramble Vest': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_bramblevest.tft_set13.png',
  'Gargoyle Stoneplate': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_gargoylestoneplate.tft_set13.png',
  'Dragon\'s Claw': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_dragonsclaw.tft_set13.png',
  'Warmog\'s Armor': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_warmogsarmor.tft_set13.png',
  'Kraken\'s Fury': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_krakenslayer.tft_tft14_5.png',
  'Deathblade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_deathblade.tft_set13.png',
  'Infinity Edge': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_infinityedge.tft_set13.png',
  'Evenshroud': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_spectralgauntlet.tft_set13.png',
  'Last Whisper': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_lastwhisper.tft_set13.png',
  'Ionic Spark': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_ionicspark.tft_set13.png',
  'Void Staff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_voidstaff.tft_tft14_5.png',
  'Sunfire Cape': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_redbuff.tft_set13.png',
  'Red Buff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_rapidfirecannon.tft_set13.png',
  'Morellonomicon': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_morellonomicon.tft_set13.png',
  'Nashor\'s Tooth': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_leviathan.tft_set13.png',
  'Archangel\'s Staff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_archangelsstaff.tft_set13.png',
  'Rabadon\'s Deathcap': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_rabadonsdeathcap.tft_set13.png',
  'Jeweled Gauntlet': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_jeweledgauntlet.tft_set13.png',
  'Titan\'s Resolve': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_titansresolve.tft_set13.png',
  'Edge of Night': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_guardianangel.tft_set13.png',
  'Sterak\'s Gage': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_steraksgage.tft_set13.png',
  'Quicksilver': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_quicksilver.tft_set13.png',
  'Hand Of Justice': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_unstableconcoction.tft_set13.png',
  'Hextech Gunblade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_hextechgunblade.tft_set13.png',
  'Bloodthirster': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_bloodthirster.tft_set13.png',
  'Blue Buff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_bluebuff.tft_set13.png',
  'Spear of Shojin': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_spearofshojin.tft_set13.png',
  'Adaptive Helm': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_adaptivehelm.tft_set13.png',
  'Guinsoo\'s Rageblade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_guinsoosrageblade.tft_set13.png',
  'Giant Slayer': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_madredsbloodrazor.tft_set13.png',
  'Striker\'s Flail': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_powergauntlet.tft_set13.png',
  'Thief\'s Gloves': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_thiefsgloves.tft_set13.png',
  'B.F. Sword': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_bfsword.tft_set13.png',
  'Chain Vest': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_chainvest.tft_set13.png',
  'Frying Pan': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_fryingpan.tft_set13.png',
  'Giant\'s Belt': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_giantsbelt.tft_set13.png',
  'Needlessly Large Rod': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_needlesslylargerod.tft_set13.png',
  'Negatron Cloak': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_negatroncloak.tft_set13.png',
  'Recurve Bow': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_recurvebow.tft_set13.png',
  'Sparring Gloves': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_sparringgloves.tft_set13.png',
  'Spatula': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_spatula.tft_set13.png',
  'Tear of the Goddess': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_tearofthegoddess.tft_set13.png',
  'Aegis of Dawn': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_aegisofdawn.tft_set16.png',
  'Aegis of Dusk': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_aegisofdusk.tft_set16.png',
  'Ahri\'s Aura': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_ahrirhythm.tft_set17.png',
  'Blacksmith\'s Gloves': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft9_item_ornnprototypeforge.tft_set13.png',
  'Blighting Jewel': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_blightingjewel.tft_set13.png',
  'Cappa Juice': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_kappajuice.tft_set16.png',
  'Corrupt Vampiric Scepter': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_cursedvampiricscepter.tft_set13.png',
  'Dawncore': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_dawncore.tft_set15.png',
  'Death\'s Defiance': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornndeathsdefiance.tft_set13.png',
  'Deathfire Grasp': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft9_item_ornndeathfiregrasp.tft_set13.png',
  'Diamond Hands': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft7_item_shimmerscalediamondhands.tft_set13.png',
  'Ekko\'s Patience': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_ekkopatience.tft_set17.png',
  'Eternal Pact': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_eternalpact.tft_set16.png',
  'Eternal Winter': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornneternalwinter.tft_set13.png',
  'Evelynn\'s Instinct': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_evelynnfang.tft_set17.png',
  'Fishbones': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_fishbones.tft_set13.png',
  'Flickerblades': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_navoriflickerplade.tft_tft14_5.png',
  'Forbidden Idol': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_forbiddenidol.tft_set13.png',
  'Gambler\'s Blade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft7_item_shimmerscalegamblersblade_hr.tft_set13.png',
  'Gold Collector': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornnthecollector.tft_set13.png',
  'Hellfire Hatchet': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_hellfirehatchet.tft_set16.png',
  'Horizon Focus': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_horizonfocus.tft_set13.png',
  'Hullcrusher': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft9_ornnitem_hullbreaker.png',
  'Infinity Force': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornninfinityforce.tft_set13.png',
  'Innervating Locket': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_innervatinglocket.tft_set13.png',
  'Kayle\'s Exaltation': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_kaylegreatsword.tft_set17.png',
  'Lesser Mirrored Persona': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_lessermirroredpersona.tft_set16.png',
  'Lich Bane': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_lichbane.png',
  'Lightshield Crest': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_lightshieldcrest.tft_set13.png',
  'Luden\'s Tempest': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_ludenstempest.tft_set13.png',
  'Manazane': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornnmuramana.tft_set13.png',
  'Mending Echoes': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_mendingechoes.tft_set16.png',
  'Mirrored Persona': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_mirroredpersona.tft_set16.png',
  'Mittens': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_mittens.tft_set13.png',
  'Mogul\'s Mail': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft7_item_shimmerscalemogulsmail.tft_set13.png',
  'Prowler\'s Claw': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_prowlersclaw.tft_set13.png',
  'Rapid Firecannon': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_rapidfirecannon.tft_set13.png',
  'Seeker\'s Armguard': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_seekersarmguard.tft_set13.png',
  'Shadow Puppet': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_shadowpuppet.tft_set16.png',
  'Silvermere Dawn': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_silvermeredawn.tft_set13.png',
  'Sniper\'s Focus': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft9_item_ornnhorizonfocus.tft_set13.png',
  'Soraka\'s Miracle': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_sorakamiracle.tft_set17.png',
  'Spectral Cutlass': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_spectralcutlass.tft_set13.png',
  'Statikk Shiv': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_stattikshiv.tft_tft14_5.png',
  'Suspicious Trench Coat': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_suspicioustrenchcoat.tft_set13.png',
  'Talisman Of Ascension': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_talismanofascension.tft_set13.png',
  'The Indomitable': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_theindomitable.tft_tft14_5.png',
  'Thresh\'s Lantern': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_threshlantern.tft_set17.png',
  'Titanic Hydra': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_titanichydra.tft_tft14_5.png',
  'Trickster\'s Glass': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft9_item_ornntrickstersglass.tft_set13.png',
  'Unending Despair': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_unendingdespair.tft_set13.png',
  'Varus\'s Obsession': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_varusobsession.tft_set17.png',
  'Void Gauntlet': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft16_artifact_voidgauntlet.tft_set16.png',
  'Wit\'s End': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_witsend.tft_set13.png',
  'Yasuo\'s Bladework': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_yasuobladework.tft_set17.png',
  'Zeke\'s Bleak Herald': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/s_zekes_herald.png',
  'Zhonya\'s Paradox': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornnzhonyasparadox.tft_set13.png',
  'Anima Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_animatech.tft_set17.png',
  'Arbiter Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_arbiter.tft_set17.png',
  'Bastion Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_bastion.tft_set17.png',
  'Brawler Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_brawler.tft_set17.png',
  'Challenger Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_challenger.tft_set17.png',
  'Dark Star Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_darkstar.tft_set17.png',
  'Marauder Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_marauder.tft_set17.png',
  'Meeple Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_meeple.tft_set17.png',
  'N.O.V.A. Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_nova.tft_set17.png',
  'Primordian Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_primordian.tft_set17.png',
  'Psionic Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_psyops.tft_set17.png',
  'Rogue Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_rogue.tft_set17.png',
  'Shepherd Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_sheperd.tft_set17.png',
  'Sniper Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_sniper.tft_set17.png',
  'Space Groove Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_spacegroove.tft_set17.png',
  'Stargazer Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_stargazer.tft_set17.png',
  'Tactician\'s Cape': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_tacticiansring.tft_set13.png',
  'Tactician\'s Crown': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_forceofnature.tft_set13.png',
  'Tactician\'s Shield': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_tacticiansscepter.tft_set13.png',
  'Timebreaker Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_timebreaker.tft_set17.png',
  'Vanguard Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_vanguard.tft_set17.png',
  'Voyager Emblem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_emblem_voyager.tft_set17.png',
  'Biomatter Preserver': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_psyops_mod_grenademod.tft_set17.png',
  'Drone Uplink': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_psyops_mod_dronemod.tft_set17.png',
  'Kayle\'s Radiant Exaltation': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_item_artifact_kaylegreatsword.tft_set17.png',
  'Malware Matrix': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_psyops_mod_chemicalcapacitormod.tft_set17.png',
  'Radiant Adaptive Helm': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_adaptivehelmradiant.tft_set13.png',
  'Radiant Archangel\'s Staff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_archangelsstaffradiant.tft_set13.png',
  'Radiant Bloodthirster': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_bloodthirsterradiant.tft_set13.png',
  'Radiant Blue Buff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_bluebuffradiant.tft_set13.png',
  'Radiant Bramble Vest': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_bramblevestradiant.tft_set13.png',
  'Radiant Crownguard': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_crownguardradiant.tft_set13.png',
  'Radiant Deathblade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_deathbladeradiant.tft_set13.png',
  'Radiant Dragon\'s Claw': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_dragonsclawradiant.tft_set13.png',
  'Radiant Edge of Night': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_guardianangelradiant.tft_set13.png',
  'Radiant Evenshroud': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_spectralgauntletradiant.tft_set13.png',
  'Radiant Gargoyle Stoneplate': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_gargoylestoneplateradiant.tft_set13.png',
  'Radiant Giant Slayer': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_giantslayerradiant.tft_set13.png',
  'Radiant Guinsoo\'s Rageblade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_guinsoosragebladeradiant.tft_set13.png',
  'Radiant Hand of Justice': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_handofjusticeradiant.tft_set13.png',
  'Radiant Hextech Gunblade': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_hextechgunbladeradiant.tft_set13.png',
  'Radiant Infinity Edge': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_infinityedgeradiant.tft_set13.png',
  'Radiant Ionic Spark': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_ionicsparkradiant.tft_set13.png',
  'Radiant Jeweled Gauntlet': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_jeweledgauntletradiant.tft_set13.png',
  'Radiant Kraken\'s Fury': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_krakenslayerradiant.tft_tft14_5.png',
  'Radiant Last Whisper': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_lastwhisperradiant.tft_set13.png',
  'Radiant Morellonomicon': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_morellonomiconradiant.tft_set13.png',
  'Radiant Nashor\'s Tooth': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_leviathanradiant.tft_set13.png',
  'Radiant Protector\'s Vow': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_frozenheartradiant.tft_set13.png',
  'Radiant Quicksilver': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_quicksilverradiant.tft_set13.png',
  'Radiant Rabadon\'s Deathcap': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_rabadonsdeathcapradiant.tft_set13.png',
  'Radiant Red Buff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_rapidfirecannonradiant.tft_set13.png',
  'Radiant Spear of Shojin': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_spearofshojinradiant.tft_set13.png',
  'Radiant Spirit Visage': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_spiritvisagerr.tft_tft14_5.png',
  'Radiant Steadfast Heart': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_nightharvesterradiant.tft_set13.png',
  'Radiant Sterak\'s Gage': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_steraksgageradiant.tft_set13.png',
  'Radiant Striker\'s Flail': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_trapclawradiant.tft_set13.png',
  'Radiant Sunfire Cape': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_sunfirecaperadiant.tft_set13.png',
  'Radiant Thief\'s Gloves': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_thiefsglovesradiant.tft_set13.png',
  'Radiant Titan\'s Resolve': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_titansresolveradiant.tft_set13.png',
  'Radiant Void Staff': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_voidstaffradiant.tft_set17.png',
  'Radiant Warmog\'s Armor': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_warmogsarmorradiant.tft_set13.png',
  'Semiconductor': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_psyops_mod_semiconductormod.tft_set17.png',
  'Sympathetic Implant': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_psyops_mod_sympatheticimplantmod.tft_set17.png',
  'Target-Lock Optics': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_psyops_mod_targetlockmod.tft_set17.png',
  'Aegis of the Legion': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_aegisofthelegion.tft_set13.png',
  'Banshee\'s Veil': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_bansheesveil.tft_set13.png',
  'Chalice of Power': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_chalice.tft_set13.png',
  'Knight\'s Vow': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_supportknightsvow.tft_set13.png',
  'Locket of the Iron Solari': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_locketoftheironsolari.tft_set13.png',
  'Moonstone Renewer': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_moonstone.tft_set13.png',
  'Needlessly Big Gem': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft7_item_shimmerscaleheartofgold_hr.tft_set13.png',
  'Obsidian Cleaver': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornnobsidiancleaver.tft_set13.png',
  'Randuin\'s Omen': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft4_item_ornnranduinssanctum.tft_set13.png',
  'Shroud of Stillness': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_shroud.tft_set13.png',
  'The Eternal Flame': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_eternalflame.tft_set13.png',
  'Unstable Treasure Chest': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_unstabletreasurechest.tft_set13.png',
  'Virtue of the Martyr': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_radiantvirtue.tft_set13.png',
  'Zeke\'s Herald': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_zekesherald.tft_set13.png',
  'Zephyr': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_zephyr.tft_set13.png',
  'Zz\'Rot Portal': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft5_item_zzrotportalradiant.tft_set13.png',
  'Broken Prototype': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_clunkyprototype_t0.tft_set17.png',
  'Leaky Prototype': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_leakyprototype_t0.tft_set17.png',
  'Sparking Prototype': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_sparkingprototype_t0.tft_set17.png',
  'Guiding Hex': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animsquaditem_guidinghex_t1.tft_set17.png',
  'Rocket Swarm': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_rocketswarm_t1.tft_set17.png',
  'Savage Slicer': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_savageslicer_t1.tft_set17.png',
  'Tentacle Slam': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_tentacleslam_t1.tft_set17.png',
  'Battle Bunny Crossbow': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_battlebunnycrossbow_t2.tft_set17.png',
  'Cyclonic Slicers': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_cyclonicslicers_t2.tft_set17.png',
  'Echoing Batblades': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_echoingbatblades_t2.tft_set17.png',
  'Iceblast Armor': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_iceblastarmor_t2.tft_set17.png',
  'Lioness\'s Lament': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_lionesslament_t2.tft_set17.png',
  'Radiant Field': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_radiantfield_t2.tft_set17.png',
  'Searing Shortbow': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_searingshortbow_t2.tft_set17.png',
  'The Annihilator': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_annihilator_t2.tft_set17.png',
  'UwU Blaster': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_uwublaster_t2.tft_set17.png',
  'Animapocalypse': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_annihilator_t3.tft_set17.png',
  'Bunny Prime Ballista': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_battlebunnycrossbow_t2.tft_set17.png',
  'Deep Freeze': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_iceblastarmor_t3.tft_set17.png',
  'Evolved Embershot': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_searingshortbow_t3.tft_set17.png',
  'Leonine Lamentation': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_lionesslament_t3.tft_set17.png',
  'OwO Blaster': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_uwublaster_t3.tft_set17.png',
  'Solar Eclipse': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_radiantfield_t3.tft_set17.png',
  'Unceasing Cyclone': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_cyclonicslicers_t3.tft_set17.png',
  'Vayne\'s Chromablades': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_echoingbatblades_t3.tft_set17.png',
  'Omniweapon': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft17_animasquaditem_omniweapon_t4.tft_set17.png',
  'Anomaly': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft13_goopitem_icon.tft_set13.png',
  'Crown of Demacia': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/crownofdemacia.png',
  'Hand of Justice': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_unstableconcoction.tft_set13.png',
  'Talisman of Ascension': 'https://tftflow.com/wp-content/uploads/tftImages/items/icon/tft_item_artifact_talismanofascension.tft_set13.png',
};
